### ISSUE TITLE
list_objects_v2 fails after upgrading the sdk

### ISSUE THREAD

**Issue by snaggen** [awslabs/aws-sdk-rust#727] opened 2023-02-02 07:20 UTC
### Describe the bug

Using older sdk:
aws-config = { version = "0.52", default-features = false, features = ["native-tls"]}
aws-sdk-s3 = { version = "0.22", default-features = false, features = ["native-tls", "rt-tokio"]}

It worked doing a listing of files on s3 using
```rust
let mut req = client.list_objects_v2().bucket(bucket).prefix(key);
```
(and later a send().await of course)

After doing the upgrade to the latest sdk:
aws-config = { version = "0.54", default-features = false, features = ["native-tls"]}
aws-sdk-s3 = { version = "0.24", default-features = false, features = ["native-tls", "rt-tokio"]}

This call suddenly fails with:
Aws Sdk Error: ServiceError(ServiceError { source: ListObjectsV2Error { kind: Unhandled(Unhandled { source: XmlDecodeError { kind: Custom(\"encountered invalid XML root: expected ListBucketResult but got StartEl { name: Name { prefix: \\\"\\\", local: \\\"ListAllMyBucketsResult\\\" }, attributes: [], closed: false, depth: 0 }. This is likely a bug in the SDK.\") } }), meta: Error { code: None, message: None, request_id: None, extras: {} } }, raw: Response { inner: Response { status: 200, version: HTTP/1.1, headers: {\"connection\": \"keep-alive\", \"x-amz-request-id\": \"564959999\", \"content-length\": \"189\"}, body: SdkBody { inner: Once(Some(b\"<?xml version=\\\"1.0\\\" encoding=\\\"utf-8\\\"?>\\n<ListAllMyBucketsResult><Owner><ID>***************</ID><DisplayName>************</DisplayName></Owner><Buckets/></ListAllMyBucketsResult>\")), retryable: true } }, properties: SharedPropertyBag(Mutex { data: PropertyBag, poisoned: false, .. }) } })

Nothing else is modified between the working and non-working version except the aws sdk version. 

Note: This call is made to a on-prem s3 server, by setting an endpoint. This should not be the issue here I assume, since it seems to actually contact the server, and the server is the same as the working version which still works with aws sdk for other platforms and languages. 

### Expected Behavior

Receive a ListObjectsV2 from the call.

### Current Behavior

Get an error as stated above.

### Reproduction Steps

Upgrade to latest sdk and call list_objects_v2

### Version

```text
aws-config = { version = "0.54", default-features = false, features = ["native-tls"]}
aws-sdk-s3 = { version = "0.24", default-features = false, features = ["native-tls", "rt-tokio"]}
```

### Environment details (OS name and version, etc.)

Fedora Linux 37

**Comment by ysaito1001** [comment] 2023-02-02 19:49
We'd like to better understand the on-prem s3 server you mentioned. It sounds like it's not the AWS-hosted S3 service, is it? Is it a proxy server that delegates HTTP requests to the AWS-hosted S3 or is it an server that internally handles and  requests and sends responses in a way AWS S3 does (which is why `aws-sdk-s3` is able to work with)?

**Comment by snaggen** [comment] 2023-02-02 19:57
It is a non-aws related file storage that uses the S3 protocol. And, I do not know much about it to be honest, since I just write a service that interacts with it. 
Still, not sure that is really the issue here since that server works with other s3 SDKs and the only thing that changed from working to non-working was the rust SDK version.

**Comment by ysaito1001** [comment] 2023-02-02 22:25
Thank you for clarifying. The issue seems to be that the server in question returns an XML that does not conform to AWS S3 service model (from which the Rust SDK is derived) after the upgrade. We'll further look into it and see if there is a way to mitigate it.

**Comment by snaggen** [comment] 2023-02-03 06:55
Well, it might not fully implement the s3 spec, like not having the ListBuckets call or something (as I said, I'm only a user of the server), but I'm not doing any ListBuckets call. The call I'm doing is 
```
ListObjectsV2 { handle: Handle { client: Client { connector: DynConnector, middleware: DynMiddleware, retry_policy: Standard { config: Config { initial_retry_tokens: 500, retry_cost: 5, ┤
no_retry_increment: 1, timeout_retry_cost: 10, max_attempts: 3, initial_backoff: 1s, max_backoff: 20s, base: 0x56101dd02870 }, shared_state: CrossRequestRetryState { quota_available: Mutex { data: 500, poisoned: false, .. } } }, operation_timeout_config: OperationTimeoutConfig { operation_timeout: None, operation_a│
ttempt_timeout: None }, sleep_impl: Some(TokioSleep) }, conf: Config }, inner: Builder { bucket: Some("bucket-name"), delimiter: None, encoding_type: None, max_keys: None, prefix: Some(""), continuation_token: None, fetch_owner: None, start_after: None, request_payer: None, expected_bucket_owner: None│
 } }
```
so, why is it getting a ListBuckets response?

**Comment by snaggen** [comment] 2023-02-03 07:52
And i just tested the call list_buckets, which actually works just fine.

**Comment by ysaito1001** [comment] 2023-02-03 17:39
We have confirmed that an example [list-objects](https://github.com/awslabs/aws-sdk-rust/blob/release-2023-01-26/examples/s3/src/bin/list-objects.rs), which uses `list_objects_v2`, works for S3 using `aws-sdk-s3` version `0.24` and `aws-config` version `0.54`.

> why is it getting a ListBuckets response?

It is up to the on-prem server in question how it handles a request for `ListObjectsV2`, so it may work for a certain version of `aws-sdk-s3` but unfortunately we cannot guarantee that it will continue working for a future version of the crate against the on-prem server.

Closing this issue as it is deemed not a bug in the Rust SDK.

**Comment by ysaito1001** [comment] 2023-02-03 20:12
Just reopened to add a comment that [issue 730](https://github.com/awslabs/aws-sdk-rust/issues/730) may help. Between `0.52` and `0.54`, the Rust SDK was integrated with Endpoints 2.0 ([release notes](https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2023-01-13)), so it's possible that you need to use `endpoint_url` when configuring the endpoint for the on-prem server (and possibly with setting [force_path_style](https://docs.rs/aws-sdk-s3/0.24.0/aws_sdk_s3/config/struct.Builder.html#method.force_path_style) to `true` on the Client config).

While it does not guarantee the suggestion above will work, I'd be curious to know how it goes. Kindly let me know.

**Comment by ysaito1001** [comment] 2023-02-03 20:13
Just reopened to add a comment that [issue 730](https://github.com/awslabs/aws-sdk-rust/issues/730) may help. Between two versions you worked on, the Rust SDK was integrated with Endpoints 2.0 ([release notes](https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2023-01-13)), so it's possible that you need to use `endpoint_url` when configuring the endpoint for the on-prem server (and possibly with setting [force_path_style](https://docs.rs/aws-sdk-s3/0.24.0/aws_sdk_s3/config/struct.Builder.html#method.force_path_style) to `true` on the Client config).

While it does not guarantee the suggestion above will work, I'd be curious to know how it goes. Kindly let me know.

**Comment by leo91000** [comment] 2023-02-04 12:49
I am using minio to pass e2e test on my CI. I can confirm using `.endpoint_url(...)` + `.force_path_style(true)` made the error go away !

**Comment by snaggen** [comment] 2023-02-05 09:37
Yes, the combination of endpoint_url and force_path_style seems to fix this issue. Thanks for the help with resolving this.

**Comment by ysaito1001** [comment] 2023-02-06 16:06
Thanks for letting us know. Glad to know it worked out. Closing this as resolved.

**Closed by ysaito1001** 2023-02-06 16:06 UTC
