### ISSUE TITLE
Retry after HTTP2 GOAWAY errors

### ISSUE THREAD

**Issue by ozgrakkurt** [awslabs/aws-sdk-rust#738] opened 2023-02-13 11:19 UTC
### Describe the bug

[2023-02-13T11:10:36Z WARN  aws_smithy_client::hyper_ext] unrecognized error from Hyper. If this error should be retried, please file an issue. err=http2 error: connection error received: not a result of an error: connection error received: not a result of an error (hyper::Error(Http2, Error { kind: GoAway(b"", NO_ERROR, Remote) }))

### Expected Behavior

Should retry

### Current Behavior

Error out

### Reproduction Steps

none

### Version

```text
aws-smithy-client = "0.54.2"
```

### Environment details (OS name and version, etc.)

docker ubuntu:latest

### Logs

[2023-02-13T11:10:36Z WARN  aws_smithy_client::hyper_ext] unrecognized error from Hyper. If this error should be retried, please file an issue. err=http2 error: connection error received: not a result of an error: connection error received: not a result of an error (hyper::Error(Http2, Error { kind: GoAway(b"", NO_ERROR, Remote) }))

**Comment by ozgrakkurt** [comment] 2023-02-13 11:22
https://github.com/golang/go/issues/18639

**Comment by Velfi** [comment] 2023-02-13 15:51
@ozgrakkurt Thanks for submitting this. Are you actually encountering this error in production right now?

**Comment by ozgrakkurt** [comment] 2023-02-13 16:53
Hey, yes. We get this regularly

**Comment by vac-adb** [comment] 2023-05-05 10:51
I can reproduce it easily with the following code.
Note that 60s sleep duration between calls is important (there was no issue with 10s sleep).

Version
aws-config = "0.55.1"
aws-sdk-cognitoidentityprovider = "0.26.0"

```rust
use aws_sdk_cognitoidentityprovider as cognitoidentityprovider;
use tokio;
use std::thread;
use std::time::Duration;

#[tokio::main(flavor = "current_thread")]
async fn main() {
    let config = aws_config::load_from_env().await;
    let client = cognitoidentityprovider::Client::new(&config);
    let username = "fake_user";
    let password ="fake_password";
    let client_id = "fake_client";
    for i in 1..4 {
        let cognito_result = client.initiate_auth().set_client_id(Some(client_id.to_string())).auth_flow(cognitoidentityprovider::types::AuthFlowType::UserPasswordAuth).auth_parameters("USERNAME", username).auth_parameters("PASSWORD", password).send().await;
        println!("Result {:}: {:?}", i, cognito_result);
        thread::sleep(Duration::from_secs(60));
    }
}
```

Results:
1. ✅ Err(ServiceError(ServiceError { ... { message: Some("User pool client fake_client does not exist.") 
2. ❌ **Err(DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper::Error(Http2, Error { kind: GoAway(b"", NO_ERROR, Remote) }), connection: Unknown } }))**
3. ✅ Err(ServiceError(ServiceError { ... { message: Some("User pool client fake_client does not exist.")

**Comment by rcoh** [comment] 2023-05-05 14:33
ah perfect! thanks for the reproducer. it's a quick fix but I wasn't able to reproduce it in tests so I wasn't able to figure out if my fix actually worked. We'll get this prioritized and fixed—or we're happy to accept a PR, the relevant code is here: 
https://github.com/awslabs/smithy-rs/blob/main/rust-runtime/aws-smithy-client/src/hyper_ext.rs#LL207C1-L224C2

If we correctly classify that error is `kind: Io` it should be fixed

**Comment by hxk1633** [comment] 2023-09-12 15:04
I get a similar error when trying to invoke dynamodb in Rust AWS SDK:
`DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: NoMatchingAuthScheme, connection: Unknown } })`
Not sure what this error means...

**Comment by rcoh** [comment] 2023-09-12 15:53
This is a different error—no matching auth scheme. Can you open a separate
issue and include some logs?

**Comment by rcoh** [comment] 2023-11-24 13:47
It looks like the fix for this was merged but then accidentally removed as part of a merge. We'll get a fix out soon

**Comment by jdisanti** [comment] 2023-12-04 18:33
The fix has been merged and will go out in a future release: https://github.com/smithy-lang/smithy-rs/pull/3250

**Comment by jdisanti** [comment] 2023-12-06 00:15
This fix for this went out in the [December 5, 2023 release](https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2023-12-05).

**Closed by jdisanti** 2023-12-06 00:15 UTC
Labels: bug, pending-release, p2
