### ISSUE TITLE
Enable customizing a client directly

### ISSUE THREAD

**Issue by rcoh** [awslabs/aws-sdk-rust#1032] opened 2024-01-04 14:13 UTC
### Describe the feature

Given a `Client`, object, I want to be able to create a new client that is identical but with small changes, e.g. with an additional interceptor added

### Use Case

I want to be able to create sub-clients for specific use cases.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

**Comment by jmklix** [comment] 2024-05-25 00:03
Closing, duplicate of https://github.com/awslabs/aws-sdk-rust/issues/634

**Closed by jmklix** 2024-05-25 00:03 UTC
Labels: feature-request, p3
