### ISSUE TITLE
Client::from_config() takes several ms to build a client

### ISSUE THREAD

**Issue by monken** [awslabs/aws-sdk-rust#975] opened 2023-11-25 21:36 UTC
### Describe the bug

I need to create many clients with different credentials and endpoint parameters. I've been using `aws_sdk_s3::Client::from_conf(config)` for that. After looking into some performance issues, I realized that `Client::from_conf(config)` takes roughly 25ms in my dev build and 2.5ms in a release build. The config configures static credentials, a region and the identity cache is disabled with `IdentityCache::no_cache()`.

I'm not able to track down where the slow path is. Any ideas how to speed this up?

### Expected Behavior

Creating a client should take microseconds.

### Current Behavior

Creating a client should take milliseconds.

### Reproduction Steps

```rs
let start = std::time::Instant::now();
let client = Client::from_conf(config);
info!("Built AWS Client in {:?}", start.elapsed());
```

### Version

```text
aws-sdk-s3 v0.36.0
aws-runtime v0.57.2
```

### Environment details (OS name and version, etc.)

Apple M2

**Comment by monken** [comment] 2023-11-26 00:58
I believe now that it takes several ms to create the hyper_14 client with rustls. However, even if I create the client manually, the time does not improve:

```rs
        let tls_connector = hyper_rustls::HttpsConnectorBuilder::new()
            .with_webpki_roots()
            .https_only()
            .enable_http1()
            .enable_http2()
            .build();
        let http_client = HyperClientBuilder::new().build(tls_connector);
```

I pass`http_client.clone()` to `Config::builder()` but the build time of the client does not improve.

**Comment by rcoh** [comment] 2023-11-27 14:10
yeah—the issue is creating the Hyper client. This is a priority to fix. Note that this _should_ only occur once per process.

**Comment by rcoh** [comment] 2023-11-27 19:13
do you have a code snippet? the connector should be cached in a lazy static so only the first client should be slow to initialize

**Comment by monken** [comment] 2023-11-27 23:56
I create a config like so:

```rs
let tls_connector = hyper_rustls::HttpsConnectorBuilder::new()
    .with_webpki_roots()
    .https_only()
    .enable_http1()
    .build();
let http_client: aws_sdk_s3::config::SharedHttpClient = HyperClientBuilder::new().build(tls_connector);

let s3config = Config::builder()
    .identity_cache(IdentityCache::no_cache())
    .region(Region::new(region))
    .endpoint_url(endpoint)
    .http_client(http_client)
    .force_path_style(true);
```

And then I create an S3 client per per set of credentials:

```rs
let config = self
    .config
    .clone()
    .set_credentials_provider(Some(aws_credentials))
    .clone()
    .build();

start = std::time::Instant::now();
let client = Client::from_conf(config);
info!("Built AWS Client in {:?}", start.elapsed());
```

I assume the `Lazy` `HTTPS_NATIVE_ROOTS` have not been evaluated before I clone the config?

**Comment by rcoh** [comment] 2023-11-28 00:59
ah—gotcha. Yeah this is from the bug where the native-tls client is always instantiated. We're working on a fix.

**Comment by jdisanti** [comment] 2023-11-29 01:27
I think the `HTTPS_NATIVE_ROOTS` initialization is a red herring here, and that https://github.com/smithy-lang/smithy-rs/pull/3269 should solve the root problem of initializing several clients costs 2-3 milliseconds each.

We should avoid loading `HTTPS_NATIVE_ROOTS` at all in the case where they're not used (when a custom client that doesn't use them is configured, for example), but that is a separate issue.

**Comment by jdisanti** [comment] 2023-12-01 01:54
This fix for this has been merged and will go out in an upcoming release (but not necessarily the next one).

**Comment by monken** [comment] 2023-12-01 02:18
Thank you!

**Comment by jdisanti** [comment] 2023-12-14 21:28
The fix for this went out in the [December 14th release](https://github.com/awslabs/aws-sdk-rust/tree/release-2023-12-14).

**Closed by jdisanti** 2023-12-14 21:28 UTC
Labels: bug, pending-release, p2
