### ISSUE TITLE
Supply serde (de)-serializable input structs

### ISSUE THREAD

**Issue by martinjlowm** [awslabs/aws-sdk-rust#382] opened 2022-01-05 08:37 UTC
### Prerequisites

- [X] I've searched for [previous similar issues](https://github.com/awslabs/aws-sdk-rust/issues) or [discussions](https://github.com/awslabs/aws-sdk-rust/discussions) and didn't find any solution.
- [X] I searched the [Developer Guide](https://docs.aws.amazon.com/sdk-for-rust/latest/dg/welcome.html) for an answer to my question.

### Question Description

https://github.com/LegNeato/aws-lambda-events currently offers structs for various Lambda inputs, but falls short when it comes to specific CloudWatch Events events, namely, API Calls via CloudTrail (for reference: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/EventTypes.html#events-for-services-not-listed).

All these calls seem to be available as input structs in the SDK but, for obvious reasons, don't depend on serde, meaning they cannot be plugged right in to type the Lambda CloudWatch events and be deserialized automatically (with camelCase renaming).

Are there any plans on supplying structs in a separate module (or perhaps even a separate crate) with serde (de-)serialization support? I think it's a bit out of scope for this project, but it also feels silly to maintain two almost identical structs in two different projects.

**Comment by martinjlowm** [comment] 2022-01-05 19:38
Yes, the need is specifically for the embedded API call via CloudTrail CloudWatch Lambda event where the `request_parameters` field is a camelcased structure. I don't know if it is guaranteed, in all scenarios, that this inner structure *always* matches API calls that the SDKs are built upon. As for structs in this project, it would only be the `*Input` structs in `input::`.

I will have a look at the remote derive functionality - I didn't know about it. Thanks for pointing that out. :)

**Comment by rcoh** [comment] 2022-03-23 17:34
closed, dupe of #269

**Closed by rcoh** 2022-03-23 17:34 UTC
Labels: feature-request
