### ISSUE TITLE
aws-lambda-rust-runtime is using http = "1.0"

### ISSUE THREAD

**Issue by ymwjbxxq** [awslabs/aws-sdk-rust#1042] opened 2024-01-14 11:28 UTC
### Describe the bug

As with other issues #1041 there is an incompatibility around the SDK

The Lambda runtime, for example:
https://github.com/awslabs/aws-lambda-rust-runtime/blob/main/Cargo.toml

It is using `http = "1.0"` and this has the effect:

mismatched types
`http::Request<lambda_http::Body>` and `Request<Body>` have similar names, but are actually distinct types
perhaps two different versions of crate `http` are being used?

### Expected Behavior

SDK version alignment 

### Current Behavior

Forced to use the old version 0.2

### Reproduction Steps

Use in the same solution:
lambda_runtime 0.9 
aws-sigv4 = "1.1.2" 

### Possible Solution

This should not even be a solution but it is the only thing right now to make it work

http = "0.2"
http_v1 = { version = "1.0.0", package = "http" }

### Version

```text
http v0.2.11
http v1.0.0
```

### Environment details (OS name and version, etc.)

All

**Comment by jmklix** [comment] 2024-02-13 17:23
Closing this issue as it is a duplicate of this tracking issue: https://github.com/awslabs/aws-sdk-rust/issues/977
Please check out the tracking issue for any updates

**Closed by jmklix** 2024-02-13 17:23 UTC
Labels: bug, duplicate
