### ISSUE TITLE
aws-smithy-client 0.54.2 breaks athena client 

### ISSUE THREAD

**Issue by erwanncloarec** [awslabs/aws-sdk-rust#736] opened 2023-02-09 08:55 UTC
### Description of the bug
After running `cargo update` on one of my project, I had errors coming from `aws-smithy-client` at runtime.
It has been updated to `0.54.2`, and by forcing it back to `=0.54.1` everything went well.

### How to reproduce
Cargo.toml
```toml
[dependencies]
tokio = { version = "*", features = ["full"]}
aws-smithy-client = { version = "=0.54.2" }
aws-sdk-athena = { version = "=0.24.0" }
aws-config = { version =  "0.54.1", default-features = false }
```
main.rs
```rust
use aws_config::retry::RetryConfig;

#[tokio::main]
async fn main() {
    let shared_config = aws_config::load_from_env().await;
    let config = aws_sdk_athena::config::Builder::from(&shared_config)
        .retry_config(RetryConfig::standard())
        .build();
    let client = aws_sdk_athena::Client::from_conf(config);
    let query_execution_id = match client
        .start_query_execution()
        .work_group("primary")
        .query_string("select count(*) from mytable")
        .send()
        .await
    {
        Ok(res) => String::from(res.query_execution_id().unwrap()),
        Err(e) => panic!("{e}"),
    };
    println!("Query running {query_execution_id}");
}
```

This codes panics with :
```
thread 'main' panicked at 'failed to construct request', src/main.rs:18:19
```
But with:
```toml
aws-smithy-client = { version = "=0.54.1" }
```
It works:
```
Query running ce628d28-b971-4823-87f8-1016ec1d5ed2
```

Note: I'm not sure if it's relevant but in my local environment, I use `AWS_PROFILE` environment variable.

**Comment by erwanncloarec** [comment] 2023-02-10 08:06
With the `DisplayErrorContext`, I ended up with "invalid URL, scheme is not http: invalid URL, scheme is not http".
When trying with `rustls` feature of `aws-config` it works fine, but with the `native-tls` it breaks. I saw that `rustls` is in the default features, so that's why it's working when using `default-features = true`.

**Comment by Velfi** [comment] 2023-02-13 20:42
It turns out this issue was caused by a tiny mistake in recent PR. [I have a fix in PR right now](https://github.com/awslabs/smithy-rs/pull/2360).

**Comment by Velfi** [comment] 2023-02-14 15:19
The PR is merged and the fix is pending release.

**Comment by LukeMathWalker** [comment] 2023-02-14 17:58
The fix has been released to crates.io - https://github.com/awslabs/smithy-rs/releases/tag/release-2023-02-14

**Closed** 2023-02-14 18:03 UTC
