### ISSUE TITLE
SQS send_message is not working

### ISSUE THREAD

**Issue by omkarium** [awslabs/aws-sdk-rust#658] opened 2022-11-04 20:11 UTC
### Describe the bug

Following this example provided https://github.com/awslabs/aws-sdk-rust/blob/main/examples/sqs/src/bin/sqs-hello-world.rs

I tried to send a simple SQSMessage but it never worked. Also, it seems that any other expression or statement which is specified after the send request, are not working working.

### Expected Behavior

Sqs send should be able to send messages. 

### Current Behavior

```rust
let rsp = client
        .send_message()
        .queue_url(queue_url)
        .message_body(&message.body)
        .message_group_id(&message.group)
        // If the queue is FIFO, you need to set .message_deduplication_id
        // or configure the queue for ContentBasedDeduplication.
        .send()
        .await?;

println!("Send message to the queue: {:#?}", rsp);
```

In the given code, firstly the `send()` is not working. I couldn't see any messages in the standard queue. Secondly, the lines after this send are not getting called. Not even the `println! ()`

### Reproduction Steps

```rust
let rsp = client
        .send_message()
        .queue_url(queue_url)
        .message_body(&message.body)
        .message_group_id(&message.group)
        // If the queue is FIFO, you need to set .message_deduplication_id
        // or configure the queue for ContentBasedDeduplication.
        .send()
        .await?;

    println!("Send message to the queue: {:#?}", rsp);
```

Or you can follow the code in this link to replicate the behavior. https://github.com/awslabs/aws-sdk-rust/blob/main/examples/sqs/src/bin/sqs-hello-world.rs

### Version

```toml
[dependencies]
aws-config = "0.51.0"
aws-sdk-sqs = "0.21.0"
tokio = { version = "1", features = ["full"] }
```

### Environment details (OS name and version, etc.)

Windows 10, VSCode, 64bit

**Comment by robtrang** [comment] 2022-12-09 00:22
I get this same behavoir on Linux (Mint 19.3) except that a message *is* sent if the utility is run on the command line. Howvever, no message is sent if i daemonize the binary (any of the rust daemon crates show the same issue) - it gets all the way up to the point of call the above client send_message and then nothing happens after that.  It's hard to believe this is a tty issue but could it be?

**Comment by jdisanti** [comment] 2022-12-09 21:23
I tested the `sqs-hello-world` example against a standard queue, and first I got:
```
Error: Unhandled(Error { code: Some("InvalidParameterValue"), message: Some("Value MyGroup for parameter MessageGroupId is invalid. Reason: The request include parameter that is not valid for this queue type."), request_id: Some("f32e43b3-9724-5047-b37f-1fbe30386085"), extras: {} })
```
But after commenting out the `message_group_id` line, it successfully sent the message and I was able to see it in the AWS console.

The `println!` below the send can get skipped if there is an error due to the `?` operator, but I would expect that error to show up in the terminal.

**Comment by ymwjbxxq** [comment] 2022-12-12 11:11
Hello,

Maybe I did not get the problem, and sorry for that, but I can send an SQS message.

```
use lambda_runtime::{run, service_fn, LambdaEvent, Error};
use serde_json::Value;

#[tokio::main]
async fn main() -> Result<(), Error> {
    let config = aws_config::load_from_env().await;
    let sqs_client = aws_sdk_sqs::Client::new(&config);

    run(service_fn(|event: LambdaEvent<Value>| {
        execute(&sqs_client, event)
    }))
    .await?;

    Ok(())
}

pub async fn execute(client: &aws_sdk_sqs::Client, event: LambdaEvent<Value>) -> Result<(), Error> {
    let sqs_url = std::env::var("SQS_QUEUE_NAME").expect("SQS_QUEUE_NAME must be set");

    let result = client
        .send_message()
        .queue_url(sqs_url)
        .message_body("hello from my queue")
        .send()
        .await?;

    println!("{:?}", result);

    Ok(())
}
```

the println return:
`SendMessageOutput { md5_of_message_body: Some("0bfdb11ec5072a3893a0e5f88d770931"), md5_of_message_attributes: None, md5_of_message_system_attributes: None, message_id: Some("46ed1df8-b458-42f8-825f-596299adac5f"), sequence_number: None }`


message_group_id should be used with FIFO and used with the example provided I get
```
{
  "errorType": "&alloc::boxed::Box<dyn core::error::Error+core::marker::Sync+core::marker::Send>",
  "errorMessage": "Error { code: \"InvalidParameterValue\", message: \"The queue should either have ContentBasedDeduplication enabled or MessageDeduplicationId provided explicitly\", request_id: \"b2661672-803d-510b-9a78-4a638c8b1a29\" }"
}
```

That will transform the code into:
```
    let result = client
        .send_message()
        .queue_url(sqs_url)
        .message_body("hello from my queue")
        .message_group_id("myid")
        .message_deduplication_id("mysuperid")
        .send()
        .await?;
```
the println return:
`SendMessageOutput { md5_of_message_body: Some("0bfdb11ec5072a3893a0e5f88d770931"), md5_of_message_attributes: None, md5_of_message_system_attributes: None, message_id: Some("56fc48d4-f70d-43c8-8de7-8a45f9520cd7"), sequence_number: Some("18874479977180912128") }`

```
[dependencies]
aws-config = "0.51.0"
aws-types = "0.51.0"
aws-sdk-sqs = "0.21.0"
lambda_runtime = "0.7.1"
serde_json = "1.0.68"
tokio = { version = "1", features = ["full"] }
```

I don't see any problem with AWS SQS

**Comment by robtrang** [comment] 2022-12-12 21:18
My post wasn't very clear. I don't see a problem using sqs sdk EXCEPT when i run the program as a daemon (using daemonize 0.41 or any other daemon create).  At that point the call to the SQS Client.send_message hangs on FUTEX_WAIT_PRIVATE and never returns.   This might not be a bug in sqs sdk per se, but i have a lot of async / await calls in the program prior to this and they all work, so why would sqs call be different? Do i need to wrap this in it's own future or something else?

**Comment by gyuho** [comment] 2023-03-15 02:32
@robtrang This doesn't seem specific to SQS. Having this issue quite frequently for S3 + EC2 APIs (ref. https://github.com/awslabs/aws-sdk-rust/issues/611 for DynamoDB issue). Do you have any updates?

**Comment by robtrang** [comment] 2023-03-15 02:38
Unfortunately no, i don't have an update. It seems to be any method i have tried that is async. Non-Async methods work fine. I am going to try just abandoning the daemon idea and using systemd to run the binary instead. Not ideal (for my use-case) but the is above my paygrade in terms of the complexity..... 

Let us know if you find anything

**Comment by jdisanti** [comment] 2023-03-15 16:58
In general, if code isn't running after an `await`, then something is probably going wrong in a section of async code in your application--either a deadlock, or a very long running synchronous process inside of an async block.

**Comment by robtrang** [comment] 2023-03-15 17:21
To be clear: If i run the async/await code (of the AWS libraries) when my application is a Daemon (using Daemonize), it hangs. If i run it as a command line client (not a daemon), it works fine. I am not sure if the issue is with Daemonize  or not. I did try other daemon libraries and they didn't work either. 
i should post this issue in a forum focussed on daemonize as i now believe it's not an "issue" per se with the AWS libs

**Comment by jdisanti** [comment] 2023-08-04 22:51
Did you find a solution for this?

**Comment by robtrang** [comment] 2023-08-04 22:58
The “fix” is to run the binary under systemd rather than “fork” it.  Apparently (and i don’t quite understand this), the Async futures stuff that aws/rust utilizes does not work on a forked instance.

Logically, i would have those a child fork of a process is a process in itself, but the semantics of the future implementation (which may change) doesn’t allow for this kind of a process.

Not very satisfactory, but a systemd running process worked for me

**Comment by jdisanti** [comment] 2023-08-04 23:21
Interesting. Thanks for the update!

I saw [an issue on Tokio](https://github.com/tokio-rs/tokio/issues/4301) that was saying that running it with a forked instance hasn't really been explored yet, but also that it might work as long as the Tokio runtime is created _after_ the fork takes place.

I'm not really familiar with how `daemonize` works, so it's hard for me to say when exactly it's forking, and if it would fork before or after the Tokio runtime is initialized (assuming `#[tokio::main]` is being used).

**Comment by jdisanti** [comment] 2023-08-04 23:23
This definitely doesn't seem like an issue with the SDK though, so I'm going to close this. I encourage you to discuss it further in the Tokio GitHub issues (assuming you're using Tokio).

**Closed** 2023-08-04 23:23 UTC
Labels: bug, p2
